export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const SEND_CONTACT_MESSAGE = 'SEND_CONTACT_MESSAGE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CREATE_USER_PROFILE = 'CREATE_USER_PROFILE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';